### ISSUE TITLE
Explanations for Inconsistent Ontologies with OWL API 5.1.14

### ISSUE THREAD

**Issue by mthl** [ignazio1977/owlexplanation#4]
Hello,

I am trying to use this package for checking inconsistencies in an OWL 2 DL ontology. I am using OWL API 5.1.14 and owlexplanation 5.0.0 but I am failing to adapt [an old example found on stackoverflow](https://stackoverflow.com/questions/33150182/how-to-get-an-explanation-for-an-inconsistency-using-the-owlexplanation-project) to OWL API v5.

Any help would be welcome.

**Comment by ignazio1977** [comment]
This version compiles on owlexplanation version 5:

    OWLOntology ont = OWLManager.createOWLOntologyManager().createOntology();
    OWLOntologyManager m = ont.getOWLOntologyManager();
    OWLDataFactory df = m.getOWLDataFactory();
    OWLClass class1 = df.getOWLClass(IRI.create("urn:test:class1"));
    OWLClass class2 = df.getOWLClass(IRI.create("urn:test:class2"));
    OWLIndividual i = df.getOWLNamedIndividual(IRI.create("urn:test:i"));
    // create an inconsistent ontology by declaring an individual member of two disjoint classes
    m.addAxiom(ont, df.getOWLDisjointClassesAxiom(class1, class2));
    m.addAxiom(ont, df.getOWLClassAssertionAxiom(class1, i));
    m.addAxiom(ont, df.getOWLClassAssertionAxiom(class2, i));
    // create the explanation generator
    ExplanationGenerator<OWLAxiom> explainInconsistency = new InconsistentOntologyExplanationGeneratorFactory(rf, 
    // these are the two arguments needed - a data factory and a supplier of ontology managers.
        OWLManager.getOWLDataFactory(), ()->OWLManager.createOWLOntologyManager(),
        1000L).createExplanationGenerator(ont);
    // Ask for an explanation of `Thing subclass of Nothing` - this axiom is entailed in any inconsistent ontology
    Set<Explanation<OWLAxiom>> explanations = explainInconsistency.getExplanations(df.getOWLSubClassOfAxiom(df
        .getOWLThing(), df.getOWLNothing()));

**Comment by mthl** [comment]
Thanks for your quick reply,

I have indeed something that is compiling but failing at runtime with an Illegal state exception.

```
Exception in thread "main" java.lang.IllegalStateException: value cannot be null at this stage
	at org.semanticweb.owlapi.util.OWLAPIPreconditions.verifyNotNull(OWLAPIPreconditions.java:56)
	at org.semanticweb.owlapi.util.OWLAPIPreconditions.verifyNotNull(OWLAPIPreconditions.java:40)
	at uk.ac.manchester.cs.owl.explanation.ordering.ExplanationOrdererImplNoManager$SeedExtractor.getTarget(ExplanationOrdererImplNoManager.java:311)
	at uk.ac.manchester.cs.owl.explanation.ordering.ExplanationOrdererImplNoManager.getOrderedExplanation(ExplanationOrdererImplNoManager.java:174)
	at org.semanticweb.owl.explanation.api.Explanation.toString(Explanation.java:149)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.io.PrintStream.println(PrintStream.java:897)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.w3id.Http.main(Http.java:41)
```

Here is the code I am running

```java
package org.w3id;

import java.util.Set;

import org.semanticweb.HermiT.ReasonerFactory;
import org.semanticweb.owl.explanation.api.Explanation;
import org.semanticweb.owl.explanation.api.ExplanationGenerator;
import org.semanticweb.owl.explanation.impl.blackbox.checker.InconsistentOntologyExplanationGeneratorFactory;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLAxiom;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLIndividual;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyManager;

public class Http {
    public static void main(String[] args) throws Exception {
        OWLOntology ont = OWLManager.createOWLOntologyManager().createOntology();
        OWLOntologyManager m = ont.getOWLOntologyManager();
        OWLDataFactory df = m.getOWLDataFactory();
        OWLClass class1 = df.getOWLClass(IRI.create("urn:test:class1"));
        OWLClass class2 = df.getOWLClass(IRI.create("urn:test:class2"));
        OWLIndividual i = df.getOWLNamedIndividual(IRI.create("urn:test:i"));
        // create an inconsistent ontology by declaring an individual member of two disjoint classes
        m.addAxiom(ont, df.getOWLDisjointClassesAxiom(class1, class2));
        m.addAxiom(ont, df.getOWLClassAssertionAxiom(class1, i));
        m.addAxiom(ont, df.getOWLClassAssertionAxiom(class2, i));
        ReasonerFactory rf = new ReasonerFactory();
        // create the explanation generator
        ExplanationGenerator<OWLAxiom> explainInconsistency =
                new InconsistentOntologyExplanationGeneratorFactory(rf,
                        OWLManager.getOWLDataFactory(),
                        OWLManager::createOWLOntologyManager,
                        1000L).createExplanationGenerator(ont);
        // Ask for an explanation of `Thing subclass of Nothing` - this axiom is entailed in any inconsistent ontology
        Set<Explanation<OWLAxiom>> explanations = explainInconsistency.getExplanations(
                df.getOWLSubClassOfAxiom(df.getOWLThing(), df.getOWLNothing()));
        explanations.forEach(System.out::println);
    }
}
```
My dependency specification is the following

```xml
  <dependencies>
    <dependency>
      <groupId>net.sourceforge.owlapi</groupId>
      <artifactId>org.semanticweb.hermit</artifactId>
      <version>1.3.8.510</version>
    </dependency>
    <dependency>
      <groupId>net.sourceforge.owlapi</groupId>
      <artifactId>owlapi-distribution</artifactId>
      <version>5.1.14</version>
    </dependency>
    <dependency>
      <groupId>net.sourceforge.owlapi</groupId>
      <artifactId>owlexplanation</artifactId>
      <version>5.0.0</version>
    </dependency>
    <dependency>
      <groupId>net.sf.trove4j</groupId>
      <artifactId>core</artifactId>
      <version>3.1.0</version>
    </dependency>
  </dependencies>
```
trove4j seems to be implicitly required by HermiT.

**Comment by m0squito** [comment]
@mthl Were you able to make this work? I know it has been a while, but I got to the same "value cannot be null at this stage" exception with a very similar setup and code as yours.
